sudo: false
language: java
services: docker

branches:
  only:
  - master

install: true
script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_deploy:
- git config --local user.name "$user"
- git config --local user.email "$email"
- export TAGS=$(git tag)
- export PREV_TAG=$(echo ${TAGS} | awk '{print $NF}')
- export VERSION=$(./getVersion.sh)
- export TRAVIS_TAG="gitlab-api-v${VERSION)"
- export IS_SNAPSHOT=$(if [[ $VERSION == *"SNAPSHOT" ]]; then echo "true"; else echo "false"; fi)
- git tag $TRAVIS_TAG

deploy:
# Only deploys release versions to github releases
  - provider: releases
    api_key:
      secure: VZvvgL4BgqHUR7mF85i66xs64JMwod0n7MKaHuITwhBS6oISSJiKJ0zBGj65VWgFOuIFGY+GgNMt9Z13ZUbDifq2yBQuXh5DMH7z0WdujRGcDdd76msib1tYU7beybge0k1kZ6ENhfZI880w4oxPZGtSoTW8q2/tQbxQYntDhEqr7BgJH7rChjjRZLCa8dg/NceIzCFMSk11QFkQOXRB/1hICuIDUJQcgKpnyJKvBJkCtlyqKwG0Ad1DuyX5ExVlov5lp1sTbnGlrEkT35MDgfs24qw5SfdXjmQoWhR/BRs+WrfRFB6I8U4el60OcxehB5SRSwuVRKnkj+bFavpl/DrrftMwcyEz9NGJ1MwLX8UZHzCLtmRFWjCkVzlqag4XoYGonoRMvja5DhC2YSaBcatwMjZ/UJ3DbqlCJXv17en+eaQGQLu6wmeQmOY4gkw8NgKcQgSGsKrltCj05At9ousJ3PKuY3NuPP4H1f5Yn6klScxz3Wj8V4cqozLZi52pexeyccKzkiEvRhoge7iP87iqPqRR6mIopXgPwkcxhGLDovmLQ71KN3rlEedbRCMnYoWzmq0RBkfS8SAvcLR3EpHqMH4NkN93kg4A5xFeI1xD66BjXjMFEaeNKcNwgxSj7WOsscjtB0mEv8cvZifzvstKDcVBikL+ZWzmzAU1Iys=
    skip_cleanup: true
    name: $TRAVIS_TAG
    body: $TRAVIS_COMMIT_MESSAGE
    file:
    - target/gitlab-api.hpi
    - target/gitlab-api.jar
    on:
      repo: jenkins-gitlab/gitlab-api-plugin
      condition: tag != env(PREV_TAG) AND env(IS_SNAPSHOT) != "true"

# Only uploads snapshots, not releases to maven.jenkins-ci.org
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy -DskipTests=true"
    skip_cleanup: true
    on:
      repo: jenkins-gitlab/gitlab-api-plugin
      condition: env(IS_SNAPSHOT) == "true"